# Generated by Django 5.1.6 on 2025-02-13 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mail_address', models.TextField()),
                ('personal_phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('reference_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('office_in_time', models.TimeField()),
                ('office_out_time', models.TimeField()),
                ('attendance_delay', models.BooleanField(default=False)),
                ('earned_leave', models.IntegerField(default=0)),
                ('sick_leave', models.IntegerField(default=0)),
                ('leave_description', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('reporting_leader', models.CharField(max_length=255)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='employee_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('office_regular_time', models.TimeField()),
                ('office_grace_time', models.TimeField()),
                ('employee_address', models.TextField()),
                ('emergency_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_details.emergencycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_details.employeedetails')),
            ],
        ),
    ]
