# Generated by Django 5.1.6 on 2025-02-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0002_emaillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
