# Generated by Django 5.1.6 on 2025-02-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cv_file', models.FileField(upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_paper', models.BooleanField(default=False)),
                ('sim_card', models.BooleanField(default=False)),
                ('visiting_card', models.BooleanField(default=False)),
                ('placement', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.cv')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='hr_work.department'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('joining_report', 'Joining Report')], max_length=50)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('sent_to_email', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.cv')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_notification_sent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interview_result', models.TextField()),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('interview_pdf', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.cv')),
            ],
        ),
        migrations.CreateModel(
            name='ITProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.BooleanField(default=False)),
                ('laptop', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.cv')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_employees', models.IntegerField()),
                ('job_description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_work.department')),
            ],
        ),
    ]
