# Generated by Django 5.1.6 on 2025-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_work', '0002_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cv_file', models.FileField(upload_to='cv_adds/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
