# Generated by Django 5.1.6 on 2025-02-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_work', '0003_cvadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorized_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized', to='hr_work.cv')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_cvs', to='hr_work.department')),
            ],
        ),
    ]
