# Generated by Django 5.1.6 on 2025-02-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_work', '0004_categorizedcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeprovision',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='financeprovision',
            name='payroll_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payrolls/'),
        ),
        migrations.AddField(
            model_name='financeprovision',
            name='sent_payroll_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
